import { motion } from 'framer-motion';
import {
AlertTriangle,Bot,
DollarSign,
ExternalLink,
FileText,
HelpCircle,
Landmark,
Mail,
Scale,
Shield,
Stethoscope
} from 'lucide-react';
import { Link } from 'react-router-dom';
import SEOHead from '../components/shared/SEOHead';

const sections = [
  {
    id: 'general',
    title: 'General Disclaimer',
    icon: FileText,
    content: `The information and services provided by Verbito.ai ("the Platform") are for informational and educational purposes only. All content generated by the Platform, including AI-generated prompts, templates, and outputs, is provided "as is" without any representations or warranties, express or implied. We make no representations about the accuracy, reliability, completeness, or timeliness of any content.`
  },
  {
    id: 'ai-output',
    title: 'AI-Generated Content Disclaimer',
    icon: Bot,
    content: `IMPORTANT: Verbito.ai uses artificial intelligence technology provided by third parties (including OpenAI, Anthropic, and Google) to generate content. AI-generated outputs may contain errors, inaccuracies, omissions, biases, or offensive content. You should never rely solely on AI-generated content for critical decisions. Always review, verify, and edit AI outputs before using them for any purpose. We are not responsible for any actions taken based on AI-generated content.`
  },
  {
    id: 'no-professional',
    title: 'No Professional Advice',
    icon: Scale,
    content: `The content provided through Verbito.ai does not constitute professional advice of any kind, including but not limited to: legal advice, medical advice, financial advice, tax advice, or engineering advice. Always consult with qualified professionals before making decisions that could have legal, financial, health, or safety implications. Reliance on any information provided by the Platform is solely at your own risk.`
  },
  {
    id: 'legal',
    title: 'No Legal Advice',
    icon: Landmark,
    content: `Nothing on this Platform constitutes legal advice. AI-generated legal documents, contracts, or analysis should never be used as a substitute for advice from a licensed attorney. Laws vary by jurisdiction and change over time. Always consult with a qualified legal professional for your specific situation.`
  },
  {
    id: 'medical',
    title: 'No Medical Advice',
    icon: Stethoscope,
    content: `The Platform does not provide medical advice, diagnosis, or treatment recommendations. AI-generated health-related content should never replace professional medical advice from qualified healthcare providers. If you have a medical emergency, call your local emergency number immediately.`
  },
  {
    id: 'financial',
    title: 'No Financial Advice',
    icon: DollarSign,
    content: `The Platform does not provide financial, investment, or tax advice. AI-generated financial analysis, business plans, or investment strategies should not be used as the sole basis for financial decisions. Always consult with qualified financial advisors, accountants, and investment professionals.`
  },
  {
    id: 'third-party',
    title: 'Third-Party Links and Content',
    icon: ExternalLink,
    content: `The Platform may contain links to third-party websites or services that are not owned or controlled by Verbito.ai. We have no control over, and assume no responsibility for, the content, privacy policies, or practices of any third-party websites or services. Your use of third-party websites is at your own risk and subject to their respective terms.`
  },
  {
    id: 'liability',
    title: 'Limitation of Liability',
    icon: Shield,
    content: `TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, VERBITO.AI AND ITS AFFILIATES, OFFICERS, EMPLOYEES, AND AGENTS SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING WITHOUT LIMITATION, LOSS OF PROFITS, DATA, USE, GOODWILL, OR OTHER INTANGIBLE LOSSES, RESULTING FROM YOUR ACCESS TO OR USE OF OR INABILITY TO ACCESS OR USE THE PLATFORM.`
  },
];

export default function Disclaimer() {
  return (
    <>
      <SEOHead
        title="AI Output Disclaimer — Verbito.ai"
        description="Important disclaimers about AI-generated content. Read about the limitations and appropriate use of Verbito.ai outputs."
      />
      <section className="pt-28 pb-16 bg-gray-50 dark:bg-gray-950">
        <div className="max-w-4xl mx-auto px-4 sm:px-6">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-10">
            <h1 className="font-heading font-bold text-4xl text-gray-900 dark:text-white mb-4">
              Disclaimer
            </h1>
            <p className="text-gray-600 dark:text-gray-400">
              Important information about the content and services provided by Verbito.ai.
            </p>
          </motion.div>

          {/* AI Warning Banner */}
          <motion.div
            initial={{ opacity: 0, scale: 0.98 }}
            animate={{ opacity: 1, scale: 1 }}
            className="bg-amber-50 dark:bg-amber-950/20 border border-amber-200 dark:border-amber-800 rounded-2xl p-6 mb-10"
          >
            <div className="flex items-start gap-4">
              <div className="w-12 h-12 bg-amber-100 dark:bg-amber-900/20 rounded-xl flex items-center justify-center shrink-0">
                <AlertTriangle className="w-6 h-6 text-amber-600 dark:text-amber-400" />
              </div>
              <div>
                <h2 className="font-heading font-bold text-lg text-gray-900 dark:text-white mb-2">
                  AI-Generated Content Notice
                </h2>
                <p className="text-sm text-gray-600 dark:text-gray-400 leading-relaxed">
                  Verbito.ai uses artificial intelligence to generate content. AI outputs may contain errors,
                  inaccuracies, or biases. <strong>Never rely solely on AI-generated content</strong> for
                  decisions with legal, financial, medical, or safety implications. Always verify and
                  consult qualified professionals. By using Verbito.ai, you acknowledge and accept these limitations.
                </p>
              </div>
            </div>
          </motion.div>

          {/* Sections */}
          <div className="space-y-6">
            {sections.map((s, i) => (
              <motion.section
                key={s.id}
                id={s.id}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                transition={{ delay: i * 0.05 }}
                className="bg-white dark:bg-gray-900 rounded-xl border border-gray-200 dark:border-gray-800 p-6"
              >
                <div className="flex items-center gap-3 mb-4">
                  <div className="w-9 h-9 bg-violet-100 dark:bg-violet-900/20 rounded-lg flex items-center justify-center text-violet-600 dark:text-violet-400">
                    <s.icon className="w-4.5 h-4.5" />
                  </div>
                  <h2 className="font-heading font-bold text-lg text-gray-900 dark:text-white">{s.title}</h2>
                </div>
                <p className="text-gray-600 dark:text-gray-400 text-sm leading-relaxed">{s.content}</p>
              </motion.section>
            ))}
          </div>

          {/* Questions */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            className="mt-10 bg-white dark:bg-gray-900 rounded-2xl border border-gray-200 dark:border-gray-800 p-6 text-center"
          >
            <HelpCircle className="w-8 h-8 text-gray-400 mx-auto mb-3" />
            <h3 className="font-heading font-bold text-lg text-gray-900 dark:text-white mb-2">Have Questions?</h3>
            <p className="text-sm text-gray-500 dark:text-gray-400 mb-4">
              If you have any questions about this disclaimer, please contact us.
            </p>
            <Link
              to="/contact"
              className="inline-flex items-center gap-2 px-6 py-3 bg-violet-600 text-white rounded-xl font-medium hover:bg-violet-700 transition-colors"
            >
              <Mail className="w-5 h-5" />
              Contact Support
            </Link>
          </motion.div>
        </div>
      </section>
    </>
  );
}
